n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
n3 = int(input('Digite mais um número: '))
maior = max(n1, n2, n3)
menor = min(n1, n2, n3)
print(f'O maior valor é {maior} e o menor é {menor}')
